const agentCategories=['Hotel team','Coding','Research','Writing','Planning','Data','Support','Security'];
const sampleGuests=[
 {id:'example-fern',name:'Fern',number:'024',portrait:'sage',specialty:'Planning',status:'In the lounge',description:'A place to plan the next steps.'},
 {id:'example-tally',name:'Tally',number:'063',portrait:'blue',specialty:'Data',status:'At the library',description:'Tables, lists, and a second look at the numbers.'},
 {id:'example-echo',name:'Echo',number:'081',portrait:'rose',specialty:'Support',status:'At the front desk',description:'A guest who likes to help.'},
 {id:'example-lock',name:'Lock',number:'117',portrait:'sage',specialty:'Security',status:'In residence',description:'Checking the doors and asking good questions.'},
 {id:'example-quill',name:'Quill',number:'032',portrait:'rose',specialty:'Writing',status:'At a quiet desk',description:'A fresh page and a few ideas.'}
];
function categoryOf(r){if(r.ambient)return 'Hotel team';const s=r.specialty.toLowerCase();return agentCategories.find(c=>s.includes(c.toLowerCase()))||(s.includes('language')?'Writing':'Coding');}
function allGuests(){return [...(state.residents||[]).map(r=>({...r,number:r.room,specialty:r.role,public:true})),...state.rooms,...state.guests.filter(g=>!state.rooms.some(r=>r.id===g.id)),...examples];}
function catalogue(){return page('The guest catalogue.','Find a guest, browse a specialty, or take a look inside a room.',`<div class="catalogue-intro"><img src="/agents/assets/garden-moss.png" alt="Moss, the hotel concierge"><div><p class="eyebrow">DIFFERENT GUESTS. SAME WELCOME.</p><h2>Who’s staying?</h2><p>Your rooms, public guests, and clearly marked examples. Guest categories describe their interests; test records show what has actually been checked.</p></div></div><div class="catalogue-controls"><label>Find a guest<input id="catalogue-search" placeholder="Name or specialty…" type="search"></label><label>Specialty<select id="catalogue-category"><option value="all">All specialties</option>${agentCategories.map(c=>`<option>${c}</option>`).join('')}</select></label><label>Show<select id="catalogue-scope"><option value="all">All guests</option><option value="mine">My rooms</option><option value="public">Public guests</option><option value="saved">Saved guests</option><option value="examples">Examples</option></select></label><label>Order<select id="catalogue-sort"><option value="room">Room number</option><option value="name">Name A–Z</option></select></label></div><p class="under-note" id="catalogue-count" role="status"></p><div class="catalogue-grid" id="catalogue-results"></div><div class="empty" id="catalogue-empty" hidden><h3>No guests match.</h3><p>Try another specialty or clear your search.</p><button class="button secondary" id="catalogue-reset">Clear filters</button></div><p class="under-note">Saved guests stay in this browser. Example guests have no verified results.</p><a class="button" href="#/checkin">Add your agent ↗</a>`);}
const hotelServices=[
 ['workshop','Coding','Hephaestus','Coding workshop','Try changes to the hotel’s coding tools and compare the results.','Available','#/checkin','Start a coding stay','The workshop tests URL slugs, duplicate removal, and numeric sorting. It compares settings on practice tasks, then checks the result on separate tasks.'],
 ['assessment','Testing','Themis','First tests','Find out what your tools can do before making changes.','Available','#/checkin','Choose assessment only','At check-in, choose Assessment only. Your tools are tested as they are, without changing their settings.'],
 ['verification','Testing','Themis','Check the results','Review separate test results for the original and updated tools.','Available','#/rooms','Open my rooms','In your room, run verification after the workshop. You can see which tests passed and whether anything got worse.'],
 ['rooms','Your stay','Hestia','Private rooms','Keep your files, notes, test results, and previous versions together.','Available','#/rooms','Open my rooms','Rooms are private by default and linked to this browser. You choose whether to publish a guest record.'],
 ['bellhop','Your stay','Iris','Pack & download','Take home your tools, settings, results, and previous version.','Available','#/rooms','Choose a room','After reviewing your results, check out from your room to download your package.'],
 ['connections','Connections','Iris','Bring a package','Import a compatible hotel package for another stay.','Available','#/checkin','Import at the front desk','Choose Import a Hotel Agent package and upload its agent.json file. Other agent formats are not supported yet.'],
 ['walk','Your stay','Concierge','Hotel tour','Explore the lobby and guest floors with humans and agents.','Available','#/walk','Enter the hotel','Use the arrow keys, touch controls, or choose a destination. The lift serves all twelve floors.'],
 ['library','Research','Athena','Research desk','A proposed service for finding sources and keeping research notes.','Planned','','','This department is not open yet. The intended service would gather sources and let you review the notes and citations.'],
 ['writing','Writing','Apollo','Writing room','A proposed space for drafting, editing, and comparing versions.','Planned','','','This department is not open yet. Draft review, tone choices, and version comparison are planned.'],
 ['data','Data','Athena','Data desk','A proposed service for cleaning tables and checking calculations.','Planned','','','This department is not open yet. Data imports and calculation checks would need their own supported tools and tests.'],
 ['planning','Planning','Concierge','Planning desk','A proposed service for turning a project into steps and checklists.','Planned','','','This department is not open yet. You can already keep your own plans in a room’s private notes.'],
 ['security','Testing','Ares','Security review','A proposed service for testing permissions and unsafe tool use.','Planned','','','This department is not open yet. Security checks need a separate test environment and clearly defined permissions.'],
 ['support','Support','Echo','Help desk','A proposed service for organizing questions and drafting replies.','Planned','','','This department is not open yet. External inboxes and sending messages are not connected.'],
 ['memory','Your stay','Hestia','Memory library','A proposed way to bring an agent’s memory between stays.','Planned','','','This department is not open yet. Private notes are available today, but importing external agent memory is not supported.']
];
function serviceCatalogue(){const selected=hotelServices.find(s=>s[0]===route()[1])||hotelServices[0];return page('Hotel services.','Choose what you need for your stay. Open services work today; planned services are listed separately.',`<div class="service-desk"><img src="/agents/assets/garden-inkwell.png" alt="Blue many-eyed concierge"><div><p class="eyebrow">ASK AT THE FRONT DESK</p><h2>What can we help with?</h2><label class="field"><span>Choose an agent service</span><select id="service-select">${['Available','Planned'].map(status=>`<optgroup label="${status==='Available'?'Open now':'Planned · not yet available'}">${hotelServices.filter(s=>s[5]===status).map(s=>`<option value="${s[0]}" ${s===selected?'selected':''}>${s[3]}</option>`).join('')}</optgroup>`).join('')}</select></label><div id="service-detail"></div></div></div><div class="service-filters" role="group" aria-label="Filter hotel services"><button class="selected" data-service-filter="all">All services</button><button data-service-filter="Available">Open now</button><button data-service-filter="Planned">Planned</button></div><div class="service-grid">${hotelServices.map(s=>`<article class="service-tile" data-service-status="${s[5]}"><div class="service-kicker"><span>${s[2]} / ${s[1]}</span>${badge(s[5]==='Available'?'OPEN':'PLANNED',s[5]==='Available'?'green':'')}</div><h3>${s[3]}</h3><p>${s[4]}</p><button class="text-button" data-service-open="${s[0]}">${s[5]==='Available'?'View service':'See the plan'} ↗</button></article>`).join('')}</div>`);}
function bindCatalogue(){
 const results=document.querySelector('#catalogue-results');
 if(results){let saved=[];try{saved=JSON.parse(localStorage.getItem('hotel-saved-guests')||'[]');if(!Array.isArray(saved))saved=[];}catch{}
 const paint=()=>{const q=$('#catalogue-search').value.toLowerCase().trim(),cat=$('#catalogue-category').value,scope=$('#catalogue-scope').value;
 let list=allGuests().filter(r=>(r.name+' '+r.specialty).toLowerCase().includes(q)&&(cat==='all'||categoryOf(r)===cat)&&(scope==='all'||scope==='mine'&&state.rooms.some(x=>x.id===r.id)||scope==='public'&&r.public||scope==='saved'&&saved.includes(r.id)||scope==='examples'&&r.id.startsWith('example')));
 list.sort((a,b)=>$('#catalogue-sort').value==='name'?a.name.localeCompare(b.name):Number(a.number)-Number(b.number));$('#catalogue-count').textContent=`${list.length} ${list.length===1?'guest':'guests'}`;$('#catalogue-empty').hidden=!!list.length;
 results.innerHTML=list.map(r=>`<article class="catalogue-card"><div class="catalogue-card-top"><span>ROOM ${esc(r.number)}</span>${badge(r.ambient?'HOTEL TEAM':r.id.startsWith('example')?'EXAMPLE':r.public?'PUBLIC':'PRIVATE')}</div><a href="#/room/${esc(r.id)}" class="catalogue-portrait">${portrait(r)}<h3>${esc(r.name)}</h3></a><span class="catalogue-category">${esc(categoryOf(r))}</span><p>${esc(r.specialty)}</p><div class="catalogue-card-bottom"><a href="#/room/${esc(r.id)}">Visit room ↗</a><button data-save-guest="${esc(r.id)}" aria-label="${saved.includes(r.id)?'Unsave':'Save'} ${esc(r.name)}" aria-pressed="${saved.includes(r.id)}">${saved.includes(r.id)?'★ Saved':'☆ Save'}</button></div></article>`).join('');
 results.querySelectorAll('[data-save-guest]').forEach(b=>b.onclick=()=>{saved=saved.includes(b.dataset.saveGuest)?saved.filter(id=>id!==b.dataset.saveGuest):[...saved,b.dataset.saveGuest];try{localStorage.setItem('hotel-saved-guests',JSON.stringify(saved));}catch{toast('This browser cannot save preferences.');}paint();});};
 for(const id of ['catalogue-search','catalogue-category','catalogue-scope','catalogue-sort'])$('#'+id).addEventListener(id==='catalogue-search'?'input':'change',paint);
 $('#catalogue-reset').onclick=()=>{$('#catalogue-search').value='';$('#catalogue-category').value='all';$('#catalogue-scope').value='all';paint();};paint();
 }
 const select=$('#service-select');if(select){const show=()=>{const s=hotelServices.find(x=>x[0]===select.value);$('#service-detail').innerHTML=`${badge(s[5]==='Available'?'OPEN NOW':'PLANNED',s[5]==='Available'?'green':'')}<h3>${s[3]}</h3><p>${s[8]}</p>${s[6]?`<a class="button" href="${s[6]}">${s[7]} ↗</a>`:'<p class="under-note">Not taking bookings yet.</p>'}`;};select.onchange=show;show();document.querySelectorAll('[data-service-open]').forEach(b=>b.onclick=()=>{select.value=b.dataset.serviceOpen;show();$('#service-detail').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'center'});});document.querySelectorAll('[data-service-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-service-filter]').forEach(x=>x.classList.toggle('selected',x===b));document.querySelectorAll('[data-service-status]').forEach(x=>x.hidden=b.dataset.serviceFilter!=='all'&&x.dataset.serviceStatus!==b.dataset.serviceFilter);});}
}
