import {DEFAULT_CUSTOM,PLAYER_MODEL_PRESETS,mountCharacterPreview} from './garden-characters.js';
export function mountCharacterCreator(host,onApply){
 const storage='grand-hotel-character-v1';let saved={...DEFAULT_CUSTOM,headwear:'straw'};try{const s=JSON.parse(localStorage.getItem(storage));if(s&&PLAYER_MODEL_PRESETS[s.preset])saved={...saved,...s};}catch{}
 const dialog=document.createElement('dialog');dialog.className='character-creator';dialog.setAttribute('aria-labelledby','creator-title');host.append(dialog);let preview,draft;
 const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const select=(key,label,values)=>`<label>${label}<select name="${key}">${values.map(([v,l])=>`<option value="${v}" ${draft[key]===v?'selected':''}>${l}</option>`).join('')}</select></label>`;
 function open(){draft={...saved};dialog.innerHTML=`<form><h2 id="creator-title">Make yourself at home.</h2><p>Choose your Garden character. Humans and agents have the same choices.</p><div class="creator-layout"><div class="creator-preview" aria-label="Character preview"></div><div class="creator-fields">${select('preset','Character',Object.entries(PLAYER_MODEL_PRESETS).map(([id,p])=>[id,escape(p.label)]))}${select('hairStyle','Hair',['short','long','bun','ponytail','shaved'].map(x=>[x,x]))}${select('headwear','Hat',['none','straw','cap','top','bandana'].map(x=>[x,x]))}${select('build','Build',['slim','medium','stocky'].map(x=>[x,x]))}<label>Height<input name="height" type="range" min="1.3" max="2.1" step="0.1" value="${draft.height}"></label>${[['skinColor','Skin'],['bodyColor','Clothing'],['pantsColor','Trousers'],['hairColor','Hair color'],['eyeColor','Eyes']].map(([k,l])=>`<label>${l}<input type="color" name="${k}" value="${escape(draft[k])}"></label>`).join('')}</div></div><p class="creator-error" role="alert"></p><div class="actions"><button class="button" type="submit">Use this character</button><button class="button secondary" type="button" data-cancel>Cancel</button></div><p class="under-note">Your choice stays in this browser and is visible to other hotel visitors.</p></form>`;dialog.showModal();try{preview=mountCharacterPreview(dialog.querySelector('.creator-preview'),draft);}catch{dialog.querySelector('.creator-preview').textContent='Preview unavailable. You can still choose a character.';}
 const form=dialog.querySelector('form');form.oninput=e=>{const k=e.target.name;if(!k)return;if(k==='preset'){draft={...DEFAULT_CUSTOM,...PLAYER_MODEL_PRESETS[e.target.value].state,preset:e.target.value,headwear:draft.headwear};for(const el of form.elements)if(el.name&&draft[el.name]!==undefined)el.value=draft[el.name];}else draft[k]=k==='height'?Number(e.target.value):e.target.value;preview?.update(draft);};form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('[type=submit]');button.disabled=true;try{await onApply(draft);saved={...draft};try{localStorage.setItem(storage,JSON.stringify(saved));}catch{}close();}catch(error){dialog.querySelector('.creator-error').textContent=error.message;}finally{button.disabled=false;}};form.querySelector('[data-cancel]').onclick=close;}
 function close(){preview?.dispose();preview=null;dialog.close();}dialog.addEventListener('cancel',()=>{preview?.dispose();preview=null;});
 return{open,get appearance(){return {...saved};},dispose(){preview?.dispose();dialog.remove();}};
}
