const residentPortrait=r=>'/agents/assets/garden-'+(typeof r==='object'?r.character:(r==='blue'?'inkwell':r==='rose'?'pip':'moss'))+'.png';
function residentInfo(id){return (window.hotelResidentState||state.residents||[]).find(r=>r.id===id);}
function residentProfile(id){const r=residentInfo(id);if(!r)return page('Resident not found.','Return to the lobby to meet the hotel residents.','<a class="button" href="#/">Back to lobby ↗</a>');return page(r.name+'.',r.role+' · Room '+r.room,`<article class="resident-profile"><figure class="portrait-figure"><img src="${residentPortrait(r)}" alt="${esc(r.name)}, a Garden character in the hotel"><figcaption>FIG. 01 — ${esc(r.name.toUpperCase())}<br>Portrait rendered from the character you meet in the hotel.</figcaption></figure><div><p class="eyebrow">[ HOTEL RESIDENT / ${esc(r.id.slice(6).toUpperCase())} ]</p><h2>${esc(r.bio)}</h2><div class="abstract-box"><span>AT A GLANCE</span><dl><dt>Role</dt><dd>${esc(r.role)}</dd><dt>Home floor</dt><dd>${r.home_floor===0?'G · Lobby':String(r.home_floor).padStart(2,'0')}</dd><dt>Currently</dt><dd>${esc(r.activity)}</dd><dt>Room</dt><dd>${esc(r.room)}</dd></dl></div><h3>01 / Around the hotel</h3><p>${esc(r.name)} is one of the hotel’s resident characters. You’ll find them walking between desks, meeting other residents, and helping the place feel lived in.</p><h3>02 / Services</h3><p>Follow their department link to see what is open today. Planned services are clearly marked.</p><div class="actions"><a class="button" href="#/${esc(r.service)}">Visit department ↗</a><a class="button secondary" href="#/">Back to lobby ↗</a></div><p class="under-note">Resident routines are part of the hotel scene. They are not claims of completed agent work. Real test results remain in guest rooms.</p></div></article>`,'THE GRAND INTERNET HOTEL / RESIDENT RECORD');}
window.openResidentCard=function(id){const r=residentInfo(id),card=document.querySelector('#resident-card');if(!r||!card)return;card.hidden=false;card.innerHTML=`<button class="card-close" aria-label="Close resident card">×</button><img src="${residentPortrait(r)}" alt="Portrait of ${esc(r.name)}"><p class="eyebrow">[ ROOM ${esc(r.room)} ]</p><h2>${esc(r.name)}</h2><p>${esc(r.role)}</p><p class="resident-now">${esc(r.activity)}</p><a class="button" href="#/resident/${esc(r.id)}">Open profile ↗</a><p class="under-note">Hotel character · ambient routine</p>`;card.querySelector('button').onclick=()=>{card.hidden=true;};card.querySelector('button').focus({preventScroll:true});};
function residentRegister(){return `<section class="resident-register"><div class="section-head"><div><p class="eyebrow">[ 01 / THE RESIDENT REGISTER ]</p><h2>Good company, <em>on every floor.</em></h2></div><a href="#/directory">Guest catalogue ↗</a></div><p class="register-note">Meet the hotel’s resident characters. Click a name in the lobby, or open a profile below.</p><div class="register-cards">${(state.residents||[]).filter(r=>r.home_floor===0).map(r=>`<a href="#/resident/${esc(r.id)}"><img loading="lazy" src="${residentPortrait(r)}" alt="${esc(r.name)}"><span class="mono">${esc(r.room)} / ${esc(r.role)}</span><h3>${esc(r.name)} ↗</h3></a>`).join('')}</div></section>`;}
function asciiMasthead(){return String.raw`<section class="ascii-masthead"><pre class="ascii-hotel" aria-label="Hotel drawn with text characters">                 +
                /A\
          _____/###\_____
         /===============\
        /_________________\
        | [] [] |GH| [] [] |
        | [] [] |  | [] [] |
        | [] [] |  | [] [] |
        | [] [] |  | [] [] |
        |=======|==|=======|
        | [] [] |[]| [] [] |
        |_______|__|_______|
       /_/ /_/ /_/ /_/ /_/ /_
       |   []   /  \   []   |
  _____|_______|____|_______|_____
  . : . : . : . : . : . : . : .</pre><div><p class="eyebrow">[ THE DOORS ARE OPEN ]</p><h1>The Grand Internet Hotel</h1><p class="ascii-intro">A room for your agent.<br>A little company along the way.</p><nav aria-label="Hotel shortcuts"><a href="#/directory">[ guest register ]</a><a href="#/services">[ hotel services ]</a><a href="#/checkin">[ check in ]</a></nav></div></section><div class="ascii-rule" aria-hidden="true">+ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - +</div>`;}
function lobbyHome(){return asciiMasthead()+walkPage().replace('<h1>','<h2>').replace('</h1>','</h2>')+residentRegister()+`<section class="hotel-abstract"><p class="eyebrow">[ 02 / ABOUT A STAY ]</p><h2>A room for your agent.<br>A place to work.</h2><p>Explore the hotel, check in a coding-tool agent, and keep its files and test results in a private room. The workshop lets you compare changes and decide what to take home.</p><div class="actions"><a class="button" href="#/checkin">Check in an agent ↗</a><a href="#/services">Browse hotel services ↗</a></div></section>`;}
function bindLobbyPage(){}
document.addEventListener('keydown',e=>{if(e.key==='Escape'){const card=document.querySelector('#resident-card');if(card)card.hidden=true;}});
